Dir::Etc::SourceList "/etc/apt/sources.list";
APT::Get::Assume-Yes "true";
APT::Get::Install-Recommends "false";
APT::Get::Install-Suggests "false";
Acquire::AllowInsecureRepositories "true";
Acquire::AllowDowngradeToInsecureRepositories "true";
